packages:
  - apps/*
  - libs/*

catalog:
  react: ^19.1.0
  react-dom: ^19.1.0
  '@react-router/dev': 7.6.3
  '@react-router/node': 7.6.3
  react-router: 7.6.3
  react-router-devtools: ^5.0.6
  '@react-router/serve': ^7.6.3
  '@hono/zod-openapi': ^0.19.10
  '@tanstack/react-query': ^5.83.0
  '@tanstack/react-query-devtools': ^5.83.0
  jotai: ^2.12.5
  zustand: ^5.0.6
  '@hookform/devtools': ^4.4.0
  '@hookform/resolvers': ^5.1.1
  react-hook-form: ^7.60.0
  zod: 3.25.76
  '@tanstack/react-table': ^8.21.3
  lucide-react: ^0.525.0
  lucide-static: 0.517.0
  motion: ^12.23.6
  next-themes: ^0.4.6
  recharts: ^2.15.4
  '@tailwindcss/typography': ^0.5.16
  '@tailwindcss/vite': ^4.1.11
  '@tailwindcss/postcss': ^4.1.11
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  tailwind-merge: ^3.3.1
  tailwind-scrollbar-hide: ^4.0.0
  tailwindcss: ^4.1.11
  tailwindcss-animate: ^1.0.7
  drizzle-orm: ^0.44.3
  drizzle-zod: 0.7.1
  '@ai-sdk/react': ^1.2.12
  ai: ^4.3.19
  '@clerk/backend': ^2.4.2
  '@testing-library/jest-dom': ^6.6.3
  '@testing-library/react': ^16.3.0
  '@testing-library/user-event': ^14.6.1
  happy-dom: ^18.0.1
  vitest: ^3.2.4
  '@vitejs/plugin-react-swc': ^3.10.2
  vite: ^6.3.5
  vite-tsconfig-paths: ^5.1.4
  '@types/node': ^24.0.14
  '@types/react': ^19.1.8
  '@types/react-dom': ^19.1.6
  typescript: ^5.9.2
  '@forge42/seo-tools': ^1.4.5
  '@inlang/cli': ^3.0.12
  '@inlang/paraglide-js': ^2.2.0
  '@novu/react': ^3.6.0
  '@uidotdev/usehooks': ^2.4.1
  countries-list: ^3.1.1
  dayjs: ^1.11.13
  decimal.js: 10.6.0
  deepmerge: ^4.3.1
  isbot: ^5.1.28
  nanoid: ^5.1.5
  nuqs: ^2.4.3
  pathcat: ^1.4.0
  posthog-js: ^1.257.0
  react-error-boundary: ^6.0.0
  react-use-audio-player: ^4.0.2
  remeda: ^2.26.0
  remix-utils: ^8.7.0
  tsx: ^4.20.3
  typeid-js: ^1.2.0
  usehooks-ts: ^3.1.1
  ws: ^8.18.3
  '@hugeicons/react': ^1.0.5
  '@hugeicons-pro/core-solid-rounded': ^1.0.14
  '@hugeicons-pro/core-duotone-rounded': ^1.0.14
  '@hugeicons-pro/core-stroke-sharp': ^1.0.14
  '@vercel/react-router': ^1.2.1
  '@dotenvx/dotenvx': ^1.47.6
  '@ai-sdk/cohere': ^1.2.10
  '@ai-sdk/openai': ^1.3.23
  '@aws-sdk/client-s3': ^3.844.0
  '@aws-sdk/s3-request-presigner': ^3.844.0
  '@metronome/sdk': 0.1.0-beta.11
  '@novu/api': ^1.5.0
  '@openrouter/ai-sdk-provider': ^0.7.2
  '@turbopuffer/turbopuffer': 0.10.5
  '@upstash/redis': ^1.35.1
  fast-json-stable-stringify: ^2.1.0
  ioredis: ^5.6.1
  stripe: ^18.3.0
  postgres: ^3.4.7
  svix: 1.69.0
  resend: ^4.6.0
  '@orpc/server': ^1.7.1
  '@orpc/client': ^1.7.1
  '@orpc/tanstack-query': ^1.7.1
